name: calma_flutter
description: "Aplicativo C'Alma para bem-estar mental e emocional"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI/Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.2

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Network & Storage
  dio: ^5.4.2
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.9
  path_provider: ^2.1.2
  uuid: ^4.4.0

  # Functional Programming & Utils
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.0

  # Routing
  go_router: ^13.2.0

  # Form validation
  formz: ^0.7.0
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.12
  
  # Testing
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets do aplicativo
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
